### PR TITLE
V10 load balanced

### LINKED ISSUE #33: Loadbalanced environments
Does this package work in loadbalanced environments, or any multi-server environment? For example, we regularly use environments with 1 back-end Umbraco server and 1+ front-end servers. If we were to switch on Maintenance Mode on the back-end Umbraco server, will that setting propagate to other servers that will then also switch to Maintenance Mode?

I performed a quick local test with 2 instances of the same website connecting to the same database and turning on Maintenance Mode on instance A does not turn on Maintenance Mode on instance B so I suppose this is not intended to work? It would be interesting if this could work, in theory Umbraco's [distributed cache refreshing mechanism](https://our.umbraco.com/documentation/reference/cache/) can be used to ping other servers to also switch to Maintenance Mode (and back out of it).

### PR DESCRIPTION
**Pull request by craigagnew**
Resolves #33 

## Summary
This PR adds support for load balanced environments. It proposes the introduction of a few ideas: 
* An `IStorageProvider` in the service code to access the appropriate place to read/write settings
* An implementation of it - `DatabaseStorageProvider` for use in load balanced setups
* A custom notification to broadcast when settings change (useful for clearing cache or sending emails)

## Testing
How to test?
Add the following to appsettings: 
```json
  "MaintenanceMode": {
    "StorageMode": "Database"
  }
```
This will trigger the switch into database storage mode, observe that settings are written to and read from the database. 

Note that without the app setting above, the code will attempt to determine whether Umbraco is in a load balanced setup and behave accordingly. 

Also @KevinJump sorry it looks like a lot of files changed but there are a lot of one-liners in the notification handlers :)

### CODE REVIEW

**Comment by KevinJump** [comment]
Thanks, this looks great, we will take a look this week, and see if we can get it merged and released 👍

**Comment by henryjump** [comment]
Hi

added a couple of changes

- Changed loadbalance detection to use the server role
- fixed a couple notifications that were checking for maintenance instead of content freeze
- added some extra checks so the setting works on a fresh install before database tables have been creates

we think checking the server role to see if umbraco thinks it's running loadbalanced is more reliable than using the config settings, but if you think that's not right, please let us know.

**Comment by craigagnew** [comment]
Hi @henryjump 

Using server role totally makes sense, I was looking for something that did exactly what you've got but couldn't find it so thanks!

And makes sense on the DB check to reduce the warnings 😄

**Comment by craigagnew** [comment]
Anything else I can contribute for this one @henryjump @KevinJump?

**Comment by henryjump** [comment]
we wanted to have a cache for the database lookups so the database doesn't get hit for every request

so this version has a `_lastChecked` value so that we only hit the database every n seconds.

the `CacheSeconds` option sets how many seconds it waits, default is 30

```json
    "MaintenanceMode": {
        "StorageMode": "Database",
        "CacheSeconds": 30
    }
```

on a local sever changes to and from maintenance mode happens instantly, but on remote servers it may take up to `CacheSeconds`

Umbraco does this for the cache on load balancing, but it checks every five seconds so maybe we could have the value lower

**Comment by craigagnew** [comment]
Good idea @henryjump. 

I wonder, to make it clear it's only for use in `Database` storage mode if we should name the setting `WaitTimeBetweenDatabaseCalls` (riffing off Umbraco's `DatabaseServerRegistrar.WaitTimeBetweenCalls` here). 

Thoughts?

**Comment by KevinJump** [comment]
Woot! - 

Merged and in v10.2.0 release - https://www.nuget.org/packages/Our.Umbraco.MaintenanceMode/10.2.0

**Pull request merged**
